famedly/synapse-invite-checker

.github/CODEOWNERS

The matrix team is probably now the primary party responsible for synapse and its modules. As such add us to the CODEOWNERS, so that we can review stuff. Not removing workflows for now, since the matrix team is quite small and it is very helpful, if sometimes externals can do reviews, when some of us are unavailable.

chore: Add matrix team to CODEOWNERS

---

README.md
synapse_invite_checker/invite_checker.py
synapse_invite_checker/rest/base.py
synapse_invite_checker/rest/contacts.py
synapse_invite_checker/rest/messenger_info.py
tests/test_simple.py

Fixes:
* #27
Specifically, this updates the schema version for the contact management api and the operator contact information.
Added a new api endpoint at `/_synapse/client/com.famedly/tim/tim-information` for providing the contact information of the operator that deployed this module.
Removed the `api_prefix` setting. It appears to be completely unused anywhere and could have led to a configuration error if utilized incorrectly
Future work for 'Pro' mode can utilize this root for other information

chore: Update versions returned by various schema

---

tests/test_config.py

Depends on #37 
because of the existence of `test_config.py`

Add a few tests to check config file exceptions when parsing fed list values

---

.github/workflows/python.yml
pyproject.toml
synapse_invite_checker/invite_checker.py
synapse_invite_checker/permissions.py
synapse_invite_checker/rest/contacts.py
synapse_invite_checker/store.py
synapse_invite_checker/types.py
tests/base.py
tests/server.py
tests/test_config.py
tests/test_contacts_api.py
tests/test_createrooms_local.py
tests/test_createrooms_remote.py
tests/test_local_invites.py
tests/test_permissions.py
tests/test_remote_invites.py
tests/test_store.py
tests/test_utils/__init__.py
tests/unittest.py
tests/utils.py

Fixes:
* #25 
Setup a new handler for permissions in Synapse's account data. 
* <b>See data loss disclaimer below.</b>
* <b>NOTE: This effectively makes that user's data instantly available to the client app as account data.</b>
Disclaimers:
* I do not know what to do about the data loss that will occur because of this. The hint of `displayName` is the more concerning of these. Does the client app have a way to find that piece of information even if they do not have access to the public profile on the remote server(excepting when there is already a shared room between the users, which feels like a dead end scenario). Loss of `start` and `end` times in the `InviteSettings` I'm more ok with.
* <del>Upstream concern: The account data being set requires an "event type" to be set. For ePA and …

Contact REST Api migration

---

README.md
synapse_invite_checker/config.py
synapse_invite_checker/invite_checker.py
tests/base.py
tests/test_config.py
tests/test_room_versions.py
tests/test_tim_information.py

This will add a check into the `on_create_room()` for verifying that the room version requested is allowed.
New configuration setting: `allowed_room_versions` which needs to be set as a list
```
allowed_room_versions:
- "9"
- "10"
```
helps with 
* famedly/product-management#2824

Check and limit room version when creating a room

---

pyproject.toml
synapse_invite_checker/invite_checker.py
tests/base.py
tests/test_room_versions.py

...and deny it based on the existing configuration setting `allowed_room_versions`
Depends on 
* famedly/synapse#18
Resolves 
* famedly/product-management#2824

Check room version requested when upgrading a room

---

README.md
synapse_invite_checker/config.py
synapse_invite_checker/invite_checker.py
tests/base.py
tests/test_config.py
tests/test_scheduled_tasks.py
tests/unittest.py

My current take on this is to use the `TaskScheduler` provided by Synapse to schedule purging rooms just as is done by the Admin API and the "room forgetting" options. This allows the worker(or main process if it isn't defined) nominated by the Synapse setting `run_background_tasks_on` to handle both, and allows for resuming these tasks after a server restart.
Running a room scan will be on a `looping_background_call()` schedule so as not to clash with any room deletions currently in progress
The `TaskScheduler` does have a few things to be aware of:
* Has a 1 minute window between checks for new work, if it is not currently active
* Allows a maximum of 5 `ScheduledTask`s to run at the same time(despite what it's docstring says)
* Resumes previously scheduled work after a server restart
A …

Remove rooms that only have EPA members left in them

---

README.md
synapse_invite_checker/config.py
synapse_invite_checker/invite_checker.py
tests/test_config.py
tests/test_room_message_timestamp.py
tests/test_scheduled_tasks.py

Resolves famedly/product-management#2829 
Find and remove inactive rooms. Do this by finding the last actual message in a room and retrieving it's time stamp. In the case that the room never had any messages(either encrypted or clear text), use the room creation event. If it was longer than the `grace_period` below, that room is scheduled for purging using the infrastructure introduced in #43 . 
Frequency of the scan itself is governed by `room_scan_run_interval`
New settings
```yaml
inactive_room_scan:
enabled: true or false # an optional switch to disable processing of this part of the room scan
grace_period: 26w # An optional value for how long to keep a room after the last eligible event,
```
New metric available for "Per-block Metrics" section:
* …

Scan and purge inactive rooms

---

synapse_invite_checker/invite_checker.py
tests/test_createrooms_local.py
tests/test_createrooms_remote.py

Resolves famedly/product-management#2825
Servers in EPA mode are not allowed to create their own public rooms. Forbid them from doing so

Disallow insurance servers from creating public rooms

---

tests/base.py
tests/test_createrooms_local.py
tests/test_createrooms_remote.py
tests/test_remote_invites.py
tests/test_scheduled_tasks.py
tests/test_utils/__init__.py

Some tests are showing their age. Comments were out of date or nor longer relevant, some remote users were missing. Also do some prep work to prepare for removing the Contacts API for EPA mode.

Refactor and test cleanup

---

synapse_invite_checker/invite_checker.py

There is no point in even having these endpoints live when in EPA mode, as no Contacts should exist on EPA servers
depends on #60

chore: Disable mounting Contacts API endpoints when in EPA mode

---

synapse_invite_checker/invite_checker.py
tests/base.py
tests/test_local_joins.py
tests/test_remote_joins.py
tests/test_utils/fake_room_creation.py

part of famedly/product-management#2826
Requires #55 
Public rooms do not require invites to join, unlike private rooms. Take advantage of this to block joining a room not on the local server if an invite does not exist
Prohibiting a join when there is an invite will be a separate pull request

feat: Forbid local user from joining remote rooms(with no invite)

---

synapse_invite_checker/invite_checker.py
tests/base.py
tests/test_remote_joins.py
tests/test_utils/fake_room_creation.py

Invites from remote servers usually have some stripped state events added to the request. Parse that data to see if the room being invited to is public, and deny if so
Requires: #58

Forbid local users being invited to remote public rooms

---

synapse_invite_checker/invite_checker.py
tests/test_createrooms_remote.py
tests/test_remote_joins.py

requires #61 
bullet point 2 of famedly/product-management#2925 
Public rooms do not require an invite to join, but placing such an invite can circumvent the required blocking. By not allowing such an invite to be created, this should prevent that circumvention

chore: Forbid local user from inviting remote user to a public room

---

README.md
synapse_invite_checker/config.py
synapse_invite_checker/invite_checker.py
tests/test_config.py
tests/test_remote_joins.py

Always disable federation with local public rooms by setting `m.federate` to `False` when creating a room. This will override what is set by any client requests.
Provides for a configuration setting to disable.
`override_public_room_federation`: "false" will stop overriding the event, default is "true"
Resolves: famedly/product-management#2926
Resolves: famedly/product-management#2948

feat: Forbid public room federation by forcing `m.federate` to False

---

synapse_invite_checker/invite_checker.py
tests/test_scheduled_tasks.py
tests/unittest.py

Resolves: famedly/product-management#2947
Instead of just outright purging an EPA server room, 'block' then 'leave' the room with local users. By blocking the room, no further activity should be possible but will allow leaves to still take place
Apparently, server notices rooms were being included in the room scan before. They are now excluded from the EPA room scan but will still be included for inactive purging

chore: Only kick insured users from their rooms, do not purge

---

README.md
synapse_invite_checker/config.py
synapse_invite_checker/invite_checker.py
tests/test_config.py
tests/test_createrooms_local.py
tests/test_utils/fake_room_creation.py

Resolves famedly/product-management#2941
Now it is forbidden to change the room's 
* `m.room.join_rules` to "public" 
* `m.room.history_visibility` to "world_readable"
Folded some previous changes that were looking at `initial_state` during room creation into this so it was no duplicated.
Rolled the prevention of changing `m.room.history_visibility` during room creation into this as well, I think it got skipped before somehow
New configuration setting:
```
prohibit_world_readable_rooms: "true" or "false"  # Defaults to "true", use "false" to disable checking for this
```

chore: Forbid changing room state event on EPA server

---

README.md
synapse_invite_checker/config.py
synapse_invite_checker/invite_checker.py
tests/test_local_invites.py

Resolves: famedly/product-management#2990
Adds configuration option to disable the DM check
```
block_invites_into_dms: true or false # defaults to "true"
```

chore: Allow to disable the DM check for invites

---

README.md
synapse_invite_checker/config.py
synapse_invite_checker/invite_checker.py
synapse_invite_checker/permissions.py
synapse_invite_checker/types.py
tests/test_permissions.py

New configuration settings allow for establishing the default permissions
```
defaultPermissions:
defaultSetting: "allow all" or "block all" # "allow all" is set as default
userExceptions:
"@example-user:server.com": # this is an example, NOTE the double quotes are necessary because of the '@' sign and the ':' at the end of the entry
serverExceptions:
"@LOCAL_SERVER@": # A useful(but not necessary) template variable to designate the local server as an exception
example.com: # an example, the ':' are necessary just as in 'userExceptions'
groupExceptions:
- groupName: isInsuredPerson # The only possible option in groupExceptions at this time. NOTE the '-' at the beginning of the entry to designate this is a list
```
Most useful examples are probably going to be:
* allow all but deny …

feat: Allow for setting default permissions in configuration

---

tests/test_createrooms_local.py
tests/test_createrooms_remote.py
tests/test_local_invites.py
tests/test_local_joins.py
tests/test_remote_joins.py

Part of famedly/product-management#2956
> * Refactor permission test cases to test all variants independent of the default and structured by the current set of requirements instead of ordered by hba user vs normal user, etc. Ideally we would have a table of invitee permissions default, server and user exceptions, inviter and invitee and expected result. (We still need SOME tests for the default case of course, see https://github.com/famedly/product-management/issues/2967 )
I do not think this got completely done as expected, but there are some decent improvements here. I dislike that the line removal from #74 seems to have been for nothing
Depends on
* #74

chore: Test permissions a little more robustly

---

CHANGELOG.md
pyproject.toml
synapse_invite_checker/invite_checker.py

- chore: Allow reactions only containing a single grapheme cluster (Jason Little)
- chore: fix type errors in `/synapse_invite_checker`, add mypy to github workflows, add hatch command `lint` (Soyoung Kim)

release: v0.4.6

---

pyproject.toml

This is not needed as of Synapse version v1.133.0
This got forgotten about for a bit, so now...
Depends on #98

chore: remove pinned version of Twisted
